<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Logo_of_the_National_Assembly_of_Azerbaijan.svg.ico" />
    <None Remove="Assets\Writing_laws2.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.4.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Logo_of_the_National_Assembly_of_Azerbaijan.svg.ico" />
    <Resource Include="Assets\TableIcon2.ico" />
    <Resource Include="Assets\Writing_laws2.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
